apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: default
  name: kustomize-hpa
spec:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kustomize-demo
  minReplicas: 1
  maxReplicas: 3