apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-demo
  namespace: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kustomize-demo
      tier: frontend
  template:
    metadata:
      labels:
        app: kustomize-demo
        tier: frontend
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: kustomize-demo
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 150m
            memory: 300Mi
          requests:
            cpu: 75m
            memory: 150Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-demo-flagr
  namespace: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kustomize-demo-flagr
      tier: frontend
  template:
    metadata:
      labels:
        app: kustomize-demo-flagr
        tier: frontend
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: kustomize-demo-flagr
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 150m
            memory: 300Mi
          requests:
            cpu: 75m
            memory: 150Mi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kustomize-hpa
  namespace: qa
spec:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120
  maxReplicas: 4
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  - resource:
      name: memory
      target:
        averageUtilization: 90
        type: Utilization
    type: Resource
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kustomize-demo
