apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-demo-flagr
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kustomize-demo-flagr
      tier: frontend
  template:
    metadata:
      labels:
        app: kustomize-demo-flagr
        tier: frontend
    spec:
      containers:
      - image: nginx
        name: kustomize-demo-flagr
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 150m
            memory: 300Mi
          requests:
            cpu: 75m
            memory: 150Mi