apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name}}
  namespace: {{ .Values.app.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels: {{ toYaml .Values.app.labels | nindent 6}}
  template:
    metadata:
      labels: {{ toYaml .Values.app.labels | nindent 8}}
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: {{ .Values.app.name}}
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 150m
            memory: 300Mi
          requests:
            cpu: 75m
            memory: 150Mi

---
{{- if eq .Values.app.namespace "qa" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-demo-flagr
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-demo-flagr
      tier: frontend
  template:
    metadata:
      labels:
        app: helm-demo-flagr
        tier: frontend
    spec:
      containers:
      - image: nginx
        name: helm-demo-flagr
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 150m
            memory: 300Mi
          requests:
            cpu: 75m
            memory: 150Mi
{{- end }}